version: '3.3'


services:
  zoo:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  consumer:
    build: ./kafka_consumer
    volumes:
      - ./configs/:/app/configs/
    environment:
      - REDIS_HOST_NAME=redis
      - REDIS_HOST_PORT=6379
      - KAFKA_HOST_NAME=kafka
      - KAFKA_HOST_PORT=9092
    links:
      - kafka:kafka

  flask:
    build: ./file_upload_server
    ports:
      - "5000:5000"
    volumes:
      - ./configs/:/app/configs/
      - ./file_storage/:/app/file_storage/
    environment:
      - FILE_DIR=file_storage/
      - KAFKA_HOST_NAME=kafka
      - KAFKA_HOST_PORT=9092
    links:
      - kafka:kafka

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"